### ISSUE TITLE
HttpRequestException: The SSL connection could not be established

### ISSUE THREAD

**Issue by RexTremendae** [ActiveLogin/ActiveLogin.Authentication#464] opened 2024-08-23 07:14 UTC
**Describe the bug**
Running the stand-alone MVC sample locally, I get "HttpRequestException: The SSL connection could not be established" without any further useful information. I have a memory that this just worked out of the box before the summer vacations (or maybe I remember wrong - maybe I have missed something critical?). If my memory is correct then it leads me to suspect that something has changed on the BankID side.

**What area is it related to**
SSL connection

**To Reproduce**
1. Start the MVC stand-alone sample locally
2. Go to https://localhost:5000
3. Click any of the login buttons (same behavior on both of them)
4. SSL connection cannot be made to BankID and an error occur

**Expected behavior**
I expect to come to the BankID login screen

**Screenshots**
![image](https://github.com/user-attachments/assets/1ba2fe19-f8da-4805-bcd6-a3c21aaf132e)

**NuGet package version**
Not using nuget, I cloned the latest repo version today, 2024-08-23

**Runtime version**
Are you using .NET Core / .NET Framework? What version?
> dotnet --list-sdks
7.0.120 [C:\Program Files\dotnet\sdk]
7.0.410 [C:\Program Files\dotnet\sdk]
8.0.108 [C:\Program Files\dotnet\sdk]
8.0.202 [C:\Program Files\dotnet\sdk]
8.0.206 [C:\Program Files\dotnet\sdk]
8.0.400 [C:\Program Files\dotnet\sdk]
9.0.100-preview.7.24407.12 [C:\Program Files\dotnet\sdk]

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Firefox 129.0.2
 - Chrome 127.0.6533.120

**Comment by EmanuelDellsen** [comment] 2024-08-24 07:12
I have the same issue but using Flutter to connect to my .Net 8 API that has the ActiveLogin NuGet installed.

**Comment by elinohlsson** [comment] 2024-08-26 06:01
If you get this error in the test environment, it is most likely caused by the fact that the test certificate used to connect to BankIDs test API has expired. The certificate is embedded in Active Login. To solve this problem, you can either upgrade to [10.0.0 RC 1](https://github.com/ActiveLogin/ActiveLogin.Authentication/releases/tag/v10.0.0-rc-1) of Active Login where the certificate is replaced with the new one (a non-prerelease will be coming soon). Or you can disable using the embedded certificate and provide the certificate yourself. Read more about how this is done here [Active Login - Test environment](https://github.com/ActiveLogin/ActiveLogin.Authentication/blob/main/docs/articles/bankid.md#test-environment) . The certificate for the test environment can be downloaded from [BankID](https://www.bankid.com/utvecklare/test)

**Comment by elinohlsson** [comment] 2024-08-27 11:25
@RexTremendae It could be that your environment does not support the encryption for the new certificate FPTestcert5_20240610.p12. The new test certificate from BankID is provided in three different versions (FPTestcert5_20240610.p12, FPTestcert5_20240610.pem and FPTestcert5_20240610-legacy.pfx). FPTestcert5_20240610.p12 is not supported on Windows Server earlier versions than 2022. Try using FPTestcert5_20240610-legacy.pfx instead.

I am currently working on a change where all the three different versions will be embedded in ActiveLogin and making it configurable which version to use. I agree that it is not optimal that the certificate is  initialized even if it is not used. I will change that too. However it should not be a problem to load the old test certificate even if it is not used.

**Comment by elinohlsson** [comment] 2024-09-27 11:58
Fixed in release 10.0.0

**Comment by elinohlsson** [comment] 2024-09-27 11:59
Fixed in release 10.0.0.

**Closed by elinohlsson** 2024-09-27 11:59 UTC
Labels: bug
