### ISSUE TITLE
Multi tenancy not supported?

### ISSUE THREAD

**Issue by antonkallenberg** [ActiveLogin/ActiveLogin.Authentication#236] opened 2020-05-07 14:56 UTC
**Describe the bug**
When adding the bank id provider multiple times following exception is thrown: 

```
InvalidOperationException: The HttpClient factory already has a registered client with the type 'ActiveLogin.Authentication.BankId.Api.IBankIdApiClient'. Client types must be unique. Consider using inheritance to create multiple unique types with the same API surface.
```

**What area is it related to**
BankID

**To Reproduce**
Create a new empty NET Core application, install the ActiveLogin-package and call AddBankId twice.

**Expected behavior**
When calling AddBankId a isolated authentication provider is created for given schema. So we can add multiple customers with different certificates. 

**Screenshots**

**NuGet package version**
ActiveLogin.Authentication.BankId.AspNetCore 2.0.1 (same behavior i 3.0.0)

**Runtime version**
NET Core 3.0 (same behavior i 3.1)

**Desktop (please complete the following information):**
 - Windows
 - Chrome

**Additional context**
Is multi tenancy something you had in mind when creating this package or was it never meant to support multiple customers with different certificates in the same application?

**Comment by PeterOrneholm** [comment] 2020-05-07 19:19
Hi Anton! Glad you are using Active Login :)

Multi tenancy is in fact supported, but using the technique you describe above. We have customers which we have helped to configure a multi tenancy setup.

As you say, the current architecture does not allow for multiple instances of `.AddBankId()`, we currently only register one BankIdClient in the IoC container and it's that client that will be used.

The solution we have for multi tenancy is the ability to, per request, select the appropriate client certificate to use for authenticating against the BankId API. This can be achieved using the [`.(UseClientCertificateResolver)`](https://github.com/ActiveLogin/ActiveLogin.Authentication/blob/master/src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdBuilderExtensions.cs#L78) extension. Using that, you'll be given all client certificates registered and can choose the correct one for the current tenant.

All other options should be configurable on a per schema basis (.AddSameDevice() etc), so you could use that.

Would the above solution for you? I'll create a separate issue to ensure we have some better docs for it and close this issue now.

**Closed by PeterOrneholm** 2020-05-07 19:19 UTC
Labels: bug

**Comment by PeterOrneholm** [comment] 2020-05-08 07:21
Added an issue at #237 to update our docs regarding multi tenancy.

**Comment by antonkallenberg** [comment] 2020-05-08 09:05
Hi Peter!

Thank you for your quick reply!

That's great! We will solve our multi tenancy feature using the UseClientCertificateResolver-extension and some kind of cookie to determinate where the end user is coming from. 

But first we need to update to latest version (Active Login, Identity Server, NET Core) to get the extension but that wont be that big of a deal :)

Thank you for bringing us Active Login!

Regards

**Comment by PeterOrneholm** [comment] 2020-05-10 08:55
> That's great! We will solve our multi tenancy feature using the UseClientCertificateResolver-extension and some kind of cookie to determinate where the end user is coming from.

Great! Yes, using a cookie and accessing that from IHttpContext accessor is one way we've solved this.

> But first we need to update to latest version (Active Login, Identity Server, NET Core) to get the extension but that wont be that big of a deal :)

Should be an easy update. A list of breaking changes can be found in the [release notes](https://github.com/ActiveLogin/ActiveLogin.Authentication/releases/tag/3.0.0).

> Thank you for bringing us Active Login!

You are welcome :)

**Comment by antonkallenberg** [comment] 2020-05-11 10:20
Hi again @PeterOrneholm,

Is there some kind of caching of resolved certificates (using UseClientCertificateResolver). I have setup a multi tenancy scenario using the same scheme... and UseClientCertificateResolver only seems to be called once per application. Do we need to have unique schemes per customer or am I missing something?

Regards,
Anton

**Comment by antonkallenberg** [comment] 2020-05-11 12:20
Would very much appreciate an example on how to correctly set this up, any code would do :) I can't get the UseClientCertificateResolver-callback to execute per customer, the callback is only called once and therefore same certificate is used for all customers. 

I have tried use same and unique scheme for all customers. :)

**Comment by PeterOrneholm** [comment] 2020-05-11 14:12
> Would very much appreciate an example on how to correctly set this up, any code would do :) I can't get the UseClientCertificateResolver-callback to execute per customer, the callback is only called once and therefore same certificate is used for all customers.

Ohh, you've found a bug! Thanks for reporting this. The project we are implementing multi tenancy for isn't live yet, and we simply haven't found this in our testing yet. It's really sad we don't have any unit test for this specific part, but the problem is that the callback is only triggered when making a real call to their API, so no easy way to fix that at the moment.

The problem is (what I can find out) is that ASP.NET caches the choice of certificate in the HttpMessageHandler pool. It seems to be cached by hostname, because usually you want to select cert based on hostname. But in our case we have multiple certificates for the same hostname.

Anyway, I'll make a hotfix to fix this issue, but until that is out, could you confirm that the below code would work? `UseClientCertificateResolver` is only an extension method to make it easier to configure, so you can try out the code below yourself before we make the hotfix. The fix is to disable caching if you enable `UseClientCertificateResolver`.
```
        public static IBankIdBuilder UseClientCertificateResolver(this IBankIdBuilder builder, Func<ServiceProvider, X509CertificateCollection, string, X509Certificate> configureClientCertificateResolver)
        {
            builder.ConfigureHttpClientHandler(httpClientHandler =>
            {
                var services = builder.AuthenticationBuilder.Services;
                var serviceProvider = services.BuildServiceProvider();

                httpClientHandler.PooledConnectionLifetime = TimeSpan.Zero;
                httpClientHandler.SslOptions.LocalCertificateSelectionCallback =
                    (sender, host, certificates, certificate, issuers) => configureClientCertificateResolver(serviceProvider, certificates, host);
            });

            return builder;
        }
```

It's not optimal, but the best/inly solution with current architecture. I've had a brief discussion with a colleague and for version 5 or similar we'd like to rearchitechture the solution to allow for a IBankIdClientFactory that you can override and provide different clients for different tenants.

If you confirm that the above works, I'll try to find time this week to release the hotfix.
